name: Create preview builds
defaults:
  tools:
    pnpm: 10.4.1
    node: 22.13.1

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  web_preview_build:
    name: Build Web
    type: deploy
    environment: preview
    params:
      alias: "{{.git_branch}}"

  android_preview_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: preview
    env:
      # Bind the deployed web preview url
      EXPO_PUBLIC_SERVER_URL: ""
