packages:
  - "apps/*"
  - "packages/*"

catalogs:
  
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19

  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  
catalog:  
 # Typescript
 typescript: ^5.7.3
