packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Typescript
  typescript: ^5.7.3
  zod: ^3.24.2
  dotenv-cli: ^8.0.0
  uploadthing: ^7.6.0
  "@clerk/nextjs": ^6.12.5

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
    "@types/node": ^20

  tailwind3:
    tailwindcss: 3.4.17

  tailwind4:
    tailwindcss: ^4.0.8

  rfh752:
    react-hook-form: ^7.52.1
    "@hookform/resolvers": ^3.9.0
