packages:
  - "apps/*"
  - "packages/*"

catalogs:
  
  # React 19 Packages
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19
  
catalog:  
 typescript: ^5.7.3
