name: Create EAS Build

on:
  workflow_run:
    workflows:
      - Create/Delete Branch for Pull Request
    types:
      - completed
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  web_preview_build:
    name: Build & Deploy Web
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    outputs:
      preview_url: ${{ steps.set_url.outputs.preview_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Install dependencies
        run: pnpm install

      - name: Export Web App
        working-directory: apps/mobile
        run: pnpm dlx expo export --platform web --dump-assetmap --no-ssg

      - name: Install EAS
        working-directory: apps/mobile
        run: npm i eas-cli --global

      - name: Download Neon DB URL Artifact
        uses: actions/download-artifact@v4
        with:
          name: neon-db-urls-pr-${{ github.event.pull_request.number }}

      - name: Load DB URL to ENV
        id: load_db_url
        run: |
          echo "DATABASE_URL=$(cat db_url_with_pooler.txt)" >> $GITHUB_ENV

      - name: Update the env in EAS
        working-directory: apps/mobile
        run: npx eas env:update --variable-name=DATABASE_URL --value=${{env.DATABASE_URL}} --variable-environment=preview --visibility=sensitive --non-interactive

      - name: Deploy Web App
        working-directory: apps/mobile
        run: eas deploy --alias=${{ github.ref_name }} --environment=preview --non-interactive

      - name: Set Alias Preview URL
        id: set_url
        run: |
          ALIAS_URL="https://chit-money-sub-nerd--${{ github.ref_name }}.expo.app"
          echo "preview_url=$ALIAS_URL" >> $GITHUB_OUTPUT

  android_preview_build:
    name: Build Android App (Preview)
    runs-on: ubuntu-latest
    needs: web_preview_build
    env:
      EXPO_PUBLIC_SERVER_URL: ${{ needs.web_preview_build.outputs.preview_url }}
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Install dependencies
        run: pnpm install

      - name: Install EAS
        working-directory: apps/mobile
        run: npm i eas-cli --global

      - name: Build Android App
        run: eas build --platform android --profile preview --non-interactive
